Added AutoPenis support
ZhengC1/PenisParser pull request #13
Opened 2017-05-04 02:33 UTC by Run1e

got bored

2017-05-04 07:40 UTC, DV8FromTheWorld requested changes
Don't include the output.txt as it isn't needed.

2017-05-04 07:45 UTC, Run1e commented
Removed output.txt.

2017-05-05 04:12 UTC, DV8FromTheWorld approved these changes

2017-05-05 04:16 UTC, merged

2017-05-05 04:16 UTC, WamboJambo commented
Tested working as of 2017-05-05 with AutoHotKey v1.1.22.03.